### ISSUE TITLE
scheduler caught exception

### ISSUE THREAD

**Issue by SimoonTech** [lucapxl/smashing_widget_nagiosxi#1]
Hi @lucapxl 

Great work getting this going, this is 100% something that would be useful for me and team.
I've current clone down your project and have hit a scheduler caught exception error (plus a 401) any ideas where I've gone wrong?
<img width="877" alt="Screen Shot 2019-08-20 at 21 00 48" src="https://user-images.githubusercontent.com/23457220/63380075-a6ef0c80-c38d-11e9-9ab0-61164c64db77.png">
<img width="1040" alt="Screen Shot 2019-08-20 at 21 01 23" src="https://user-images.githubusercontent.com/23457220/63380099-b1a9a180-c38d-11e9-9d32-de3ea9b60d91.png">

**Comment by lucapxl** [comment]
Hi @SuperDuperOne,

looking at the images you provided it seems to me the error is coming from the other dashboard installed "Pingdomuptime". Once the scheduler fails it won't run other scheduled jobs either. 
Can you try to run my widget on an empty Dashboard and see if there works?

**Comment by SimoonTech** [comment]
Hi @lucapxl 
Thanks for getting back to me, 
making the changes you mentioned please see attached.
<img width="1680" alt="Screen Shot 2019-08-21 at 23 00 30" src="https://user-images.githubusercontent.com/23457220/63471624-90b57f00-c467-11e9-8cd9-ef2f0f6373aa.png">

I noticed that we get 200 initially, then it just hits that scheduler caught exception:




```orrie@macbookpro:/Users/orrie/sandbox/dashing_dashboard/webdev_dash $ dashing start
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
127.0.0.1 - - [21/Aug/2019 22:59:03] "GET /nagiosxi HTTP/1.1" 200 1584 0.0019
127.0.0.1 - - [21/Aug/2019 22:59:03] "GET /events HTTP/1.1" 200 - 33.8277
127.0.0.1 - - [21/Aug/2019 22:59:03] "GET /views/nagiosxihosts.html HTTP/1.1" 200 848 0.0008
127.0.0.1 - - [21/Aug/2019 22:59:03] "GET /views/nagiosxiservices.html HTTP/1.1" 200 924 0.0009
127.0.0.1 - - [21/Aug/2019 22:59:13] "GET /nagiosxi HTTP/1.1" 200 1584 0.0020
127.0.0.1 - - [21/Aug/2019 22:59:13] "GET /events HTTP/1.1" 200 - 10.2618
127.0.0.1 - - [21/Aug/2019 22:59:13] "GET /views/nagiosxihosts.html HTTP/1.1" 200 848 0.0008
127.0.0.1 - - [21/Aug/2019 22:59:13] "GET /views/nagiosxiservices.html HTTP/1.1" 200 924 0.0007
================================================================================================================================================================
scheduler caught exception:
execution expired
scheduler caught exception:================================================================================
scheduler caught exception:
================================================================================
scheduler caught exception:
================================================================================

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `open'execution expired
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
execution expired
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'```

**Comment by lucapxl** [comment]
I see a "Execution Expired"
are you able to access the API pages of your nagios from your browser?
you can access the pages from here;
http://**YOURNAGIOSIP**/nagiosxi/api/v1/objects/servicestatus?apikey=**YOURAPIKEY**
and
http://**YOURNAGIOSIP**/nagiosxi/api/v1/objects/hoststatus?apikey=**YOURAPIKEY**

did you block the access to HTTP and only allow to HTTPS perhaps?

**Comment by SimoonTech** [comment]
Hi @lucapxl 
i'm now hitting this error: 

```
Scheduler caught exception:
785: unexpected token at ''
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/root/Desktop/webdev_dash/jobs/nagiosxi.rb:17:in `block in <top (required)>'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
```

is the below needed in the config.ru file?

```
require 'dashing'

configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'

  helpers do
    def protected!
      # Put any authentication code you want in here.
      # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

run Sinatra::Application
```

**Comment by lucapxl** [comment]
Hi @SuperDuperOne, for my widget you don't need to modify the config.ru file, only the jobs/nagiosxi.rb file.
are you able to see the json file opening the link in my previous comment?

**Comment by SimoonTech** [comment]
Hi @lucapxl 
yes, I'm able to see the json output when going to link (plus with my apikey at the end of it) 
we have traffic enabled for both http and https. 
but we keep running into:

> ```Scheduler caught exception:
> 785: unexpected token at ''
> /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
> /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
> /root/Desktop/webdev_dash/jobs/nagiosxi.rb:17:in `block in <top (required)>'
> /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
> /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
> /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

what does this mean?
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/json-2.2.0/lib/json/common.rb:156:in `parse'

```
my Current Gemfile is this:
source 'https://rubygems.org'
gem 'google-api-client'
gem 'dashing'
require 'open-uri'
gem 'json'
gem 'dotenv'
#gem 'activesupport'
#gem 'time_diff'
#gem 'rest-client'
#gem 'faraday_middleware'
gem 'rufus-scheduler'
```
can you share your Gemfile, if possible?
what version of Ruby are you using?
maybe I need a certain version updated because I read that rufus-scheduler 2.0.24 doesnt work well with dashing. (https://github.com/jmettraux/rufus-scheduler)

**Comment by lucapxl** [comment]
I am running ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux] on Centos
my gemfile is:
```Gemfile
source 'https://rubygems.org'
gem 'smashing'
gem 'nokogiri'
gem 'json'
gem 'rest-client'
```

**Comment by lucapxl** [comment]
@SuperDuperOne were you able to solve the problem?

**Comment by SimoonTech** [comment]
Hi @lucapxl 
I've been testing all weekend and unfortunately, no success, for some reason we keep hitting this error: 

785: unexpected token at ''
/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/json-2.2.0/lib/json/common.rb:156:in `parse'

I'll keep trying tomorrow, I'm determined to get this working as it would be a great widget for what we need here.

**Comment by SimoonTech** [comment]
Hi @lucapxl  

working now 👍  thanks for the help on this -- we're going to get stuck in with:

(https://github.com/lucapxl/smashing_widget_messages) 

so we can have the messages along side the errors etc 

![image (6)](https://user-images.githubusercontent.com/23457220/63781458-b0262f00-c8e1-11e9-91e8-b55ad8851d79.png)
