### ISSUE TITLE
Dashboard - Not displaying information

### ISSUE THREAD

**Issue by nolanRatu** [lucapxl/smashing_widget_nagiosxi#2]
Hi, i have got the project setup and running however its not showing the data - just a black page.
Do you have any ideas?

![dashboard-issue](https://user-images.githubusercontent.com/1127932/65290265-ae7b1e80-dba2-11e9-961e-d9a32ea88f6d.PNG)

**Comment by lucapxl** [comment]
Hi, did you add the widget to the dashboard? do you have a screenshot of the dashboard?

**Comment by nolanRatu** [comment]
Hi Lucapxl/Smashing_widget_nagiosxi

Yes I have added the widget, jobs and dashboard files from your master repo
and added them to my project, but it does not show when starting and
viewing on localhost:3030 I am a bit of a noob I have not done this for
while.

Are you saying I need to add a widget to the dashboard in the Nagios xi
dashboard?

Thanks
Nolan.

**Comment by nolanRatu** [comment]
Here is screen shot
[image: image.png]

**Comment by lucapxl** [comment]
do you have a screenshot of the page when you connect to the localhost:3030?

**Comment by nolanRatu** [comment]
Hi Lucapxl

![dashboard-nagios](https://user-images.githubusercontent.com/1127932/65641261-6e071f00-e040-11e9-87c4-81657c29182e.PNG)
![dashboard-sample](https://user-images.githubusercontent.com/1127932/65641262-6e071f00-e040-11e9-895f-1ad3db381559.PNG)
![dashboard-sampletv](https://user-images.githubusercontent.com/1127932/65641263-6e071f00-e040-11e9-8ee6-995733ba0c67.PNG)

**Comment by lucapxl** [comment]
all dashboards are empty. it seem to me a problem with smashing itself. are you able to display other widgets?

**Comment by nolanRatu** [comment]
Hi Lucapxl

No, its the same.
Is it because I am using a trial version of NagiosXI?

**Comment by nolanRatu** [comment]
I have it sorted now, I did not have node.js installed.
Thanks.
